/*
 * This source file was generated by the Gradle 'init' task
 */
package com.authService;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;

@SpringBootApplication
@EnableJpaRepositories(basePackages = {"com.authService.repositories"})
public class App {

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);

    }
}
